2024-12-12 22:06:52.890 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration artnet_led which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-12 22:06:52.890 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-12 22:07:40.958 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from dynamic-176-005-133-076.176.5.pool.telefonica.de (176.5.133.76). Requested URL: '/auth/login_flow/02b931f9605174d7cae55c6c382c6cc3'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
2024-12-12 22:08:02.114 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from dynamic-176-005-133-076.176.5.pool.telefonica.de (176.5.133.76). Requested URL: '/auth/login_flow/02b931f9605174d7cae55c6c382c6cc3'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
2024-12-12 22:08:26.598 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from dynamic-176-005-133-076.176.5.pool.telefonica.de (176.5.133.76). Requested URL: '/auth/login_flow/0d303785ae95a0398cf00509833a7f44'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
2024-12-12 22:10:15.381 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from dynamic-176-005-133-076.176.5.pool.telefonica.de (176.5.133.76). Requested URL: '/auth/login_flow/f2bd8c046ec8704240218d8c636e1a64'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
2024-12-12 22:11:36.348 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547920647440] Error handling message: Unknown error (unknown_error) Hausmeistersteuerung from 192.168.178.219 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/config/auth_provider_homeassistant.py", line 61, in websocket_create
    await hass.auth.async_link_user(user, credentials)
  File "/usr/src/homeassistant/homeassistant/auth/__init__.py", line 343, in async_link_user
    raise ValueError("Credential is already linked to a user")
ValueError: Credential is already linked to a user
